config/routes.rb
#this file is in charge of what URL corresponds with what view/webpage
Rails.application.routes.draw do
  
  #set index page/ root URL
  root 'pages#home'

  get 'pages/portfolio'

  get 'pages/about' 

  get 'pages/contact'

  get 'pages/demtales'

  get 'pages/obamify'

  get 'pages/saycel'
  
  get 'pages/paintings'

  get 'pages/docday'

  get 'pages/bearhug'

  get 'pages/outrage'

  get 'pages/minion'

  get 'pages/frenchcounter'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def portfolio
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://www.gstatic.com/firebasejs/3.8.0/firebase.js"></script>


    <title>Tanya Campbell</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  </head>

  <body>
    <%= yield %>

	
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
<button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>

    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>

  
    <br>
    </br>
    <br>
    </br>
    <br>
    </br>

    <div id="about-content">
      <center><h1 id="about-title">Hi, my name is Tanya.</h1>
        <div id = "about-des">
          <p>I am a Web Developer with 3 years of experience.</p>
          <p>I have a background in Electrical Engineering Technology & Painting.</p>
           <p>I recieved my Masters degree in Interactive Telecommunications from <a href="https://tisch.nyu.edu/itp">NYU ITP</a>.</p>
        </div>
     </center>

   
    </br>
    <br>
    </br>

      <h4>Press:</h4>
        <ul id="press-links">
          <li><a href="https://medium.com/@itpnyu/itps-obamathon-2e74b1bef9e9">ITP Obamathon</a></li>
          <li><a href="http://makezine.com/2015/05/27/sweat-hugs-vr-ar-itp-spring-show/">BearHug on MakeZine.com</a></li>
          <li><a href="https://vimeo.com/123023527">Museum of Moving Image - Drawing on Everything</a></li>
        </ul>
      
      

      <h4>Development Skills:</h4>
      <ul>
        <li>HTML5</li>
        <li>CSS3</li>
        <li>Sass</li>
        <li>Javascript</li>
        <li>jQuery</li>
        <li>Wordpress</li>
        <li>Github</li>
      </ul>
        <h4>Design Skills:</h4>
      <ul>
        <li>Adobe Photoshop</li>
        <li>Adobe Illustrator</li>
        <li>Adobe After Effects</li>
        <li>Adobe Premiere Pro</li>
      </ul>

      <h4>Details About My Website:</h4>
      <p>This website was built from scratch by me. Ruby on Rails was used as its base and jQuery for basic animations. CSS was written in Sass, and I followed organized design concepts with consideration for mobile platforms. </p>
    </div>

</html>

app/views/pages/bearhug.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
      <br>
      </br>
      <br>
      </br>
      <center>
      <div id="project-img">


        <div id="project-row">
          <a href="https://www.demtales.org/">
              <center>
          <%=image_tag("BEARHUG.jpg", width: '500px', height: '400px')%>
          <p>An Image of the BearHug Cabinet at the ITP '15 Spring Show</p>

          <iframe src="https://player.vimeo.com/video/126887768" width="500" height="288" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <p>Here is a video demonstrating the games featured on BearHug.</p>

           <%=image_tag("arcade14.jpg", width: '500px', height: '400px')%>
          <p>Sketching our cabinet design.</p>
          <%=image_tag("arcade2.jpg", width: '500px', height: '475px')%>
          <p>A sketch of our final design/vision.</p>

          <%=image_tag("arcade1.jpg", width: '500px', height: '550x')%>
          <p>We used a CRT monitor inside the arcade cabinet, here is how we secured it inside.</p>
          <%=image_tag("arcade4.jpg", width: '500px', height: '550px')%>
          <p>To make the bottom half of our cabinet, we CNC'd the appropriate dimensions and secured it together.</p>
          <%=image_tag("arcade3.jpg", width: '500px', height: '350px')%>
          <p>After adding wheels to the bottom of our cabinet.</p>


          <%=image_tag("arcade5.jpg", width: '500px', height: '550px')%>
          <p>Making sure everything fits together nicely.</p>
          <%=image_tag("arcade6.jpg", width: '500px', height: '550px')%>
          <p>Testing to see what would be the right size for our giant gummy bear display. Yes, it was edible.</p>
          <%=image_tag("arcade7.jpg", width: '500px', height: '550px')%>
          <p>Painting the cabinet.</p>
      
          <%=image_tag("arcade9.gif", width: '500px', height: '400px')%>
          <p>Final stages of securing and sizing the dial controller.</p>
          <%=image_tag("arcade10.jpg", width: '500px', height: '400px')%>
          <p>Used 'L' brackets to secure the giant gumy bear display.</p>

          <%=image_tag("arcade11.jpg", width: '500px', height: '400px')%>
          <p>The giant gummy bear, finally mounted!</p>
          <%=image_tag("arcade12.jpg", width: '500px', height: '400px')%>
          <p>Lighting up the gummy bears.</p>
          <%=image_tag("arcade13.jpg", width: '500px', height: '550px')%>
          <p>Setting up for the ITP '15 Spring Show.</p>
          
              </center>

          </a>
        </div>

        <div id="project-des">
          <h1 id="project-title">BearHug - An Arcade Cabinet</h1>

      <p>BearHug is a non-traditional arcade cabinet featuring two non-traditional digital games that put your reflex and cognitive skills to the test. In Gummy Bear Tease, players puzzle through brain teasing color matching exercises. In First Person Hugger, players decide through observation whether or not characters want to be hugged. Both games use non-traditional game controllers: any acrylic hexagon dial and two mannequin hands.
      <br><br>
      My role in this project:
      <br>
      Unity3D game development using Javascript, game controller fabrication, circuit fabircation and digital fabrication using a CNC router and a 50W laster cutter, design and UX.</p>



      <p>DEM Tales is an interactive, animated, STEM enriched mobile platform. DEM Tales is a call-to-action project to support and provide an alternative curriculum to underserved NYC students.</p>
    </p>

      </div>

    </div>

    <br>
    </br>
    <center>

    <center><div id = "folio-link"><%=link_to 'Back to Portfolio', pages_portfolio_url %></div></center>
    



  </body>
  <html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">

  </head>
  <body id="contact-body" >

    <button class="hamburger hamburger--spring" type="button">
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>

    <br>
    </br>
    <br>
    </br>
        <br>
    </br>
    <br>
  </br>
        <div id = "social-flats">
       <div id='linked-flat'> 
        <a href="https://www.linkedin.com/in/tanya-campbell-8b924935/" target="blank">
          <%= image_tag("linkedin-flat.png", width: '40px', height: '40px')%>
        </a>
      </div>
       <div id='git-flat'>
        <a href="https://github.com/tcampbellsoup" target="blank">
          <%= image_tag("github-flat.png", width: '40px', height: '40px')%>
        </a>
      </div>
       <div id='vimeo-flat'>
        <a href="https://vimeo.com/tanyacampbell" target="blank">
          <%= image_tag("vimeo-flat.png", width: '40px', height: '40px')%>
        </a>
      </div>
<!--        <div id='gram-flat'>
        <a href="https://www.instagram.com/artbyteedawg/" target="blank">
         <%= image_tag("gram-flat.png", width: '40px', height: '40px')%>
       </a>
     </div> -->
   </div>
    <div id="about-content">

     <p id="email">
        Do you have a project that you'd like for me to help with?<br></br> Send me an email at: <a id="contact-email">tanyadotcampbell@gmail.com</a>
     </p>
 
     <!-- <p>Or, fill out the fields below and I will reach out to you as soon as possible:</p>
     <br>
     <br>
  
    <div id="user-contact">

    <label for="name">Full Name:</label>
    <input id="name-field" name="name" width="400px">
    <br>
    <br>
    <label for="email">Email Address:</label>
    <input id="user-email" name="email">
    <br>
    <br>
    <label for="message">Message:</label>
    <textarea></textarea>
    <br>
    <br>
  
    <div id="submit-button">Send</div>
    
    </div>
    <br>
    <br> -->

    <div id="contact-avatar" >
      <%= image_tag("aboutmefro.png", width: '675px', height: '570px')%>
    </div>



  </body>

</html>

app/views/pages/demtales.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
      <br>
      </br>
      <br>
      </br>
      <center>
      <div id="project-img">


        <div id="project-row">
          <a href="https://www.demtales.org/">
          		<center>
					<%=image_tag("demtales.png", width: '500px', height: '400px')%>
          <p>A middle school student usertesting the DEM Tales platform.</p>

					<iframe src="https://player.vimeo.com/video/166406754" width="500" height="288" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					<p>My DEM Tales Presentation During Thesis Week.</p>
					<iframe src="https://player.vimeo.com/video/164673545" width="500" height="288" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					<p>Demo Video of DEM Tales.</p>
					<%=image_tag("demtalesinteraction.jpg", width: '500px', height: '288px')%>
					<p>Quick Wireframe of DEM Tales Mobile Experience.</p>
					<%=image_tag("animationPeak2.gif", width: '500px', height: '400px')%>
					<p>An After Effects Milestone for the Math Episode.</p>
					<%=image_tag("chardes.png", width: '500px', height: '350px')%>
					<p>Quick Snapshot of the Character Design Process.</p>
					<%=image_tag("usertest2.png", width: '500px', height: '400px')%>
					<p>Students user testing DEM Tales.</p>

          <%=image_tag("11-pre.JPG", width: '236px', height: '726px')%>
          <p>A pre-test taken by a junior before watching Math Episode.</p>
          <%=image_tag("11-post.JPG", width: '236px', height: '726px')%>
          <p>A post-test taken by a junior before watching Math Episode.</p>
          <%=image_tag("episodeorganize.JPG", width: '500px', height: '400px')%>
          <p>A quick snapshot of organizing my Fractions Episode.</p>
          <%=image_tag("claymation.JPG", width: '500px', height: '400px')%>
          <p>Early stages of scultping and molding.</p>
					
          		</center>

          </a>
        </div>

        <div id="project-des">
          <h1 id="project-title">Dope Engineering + Math (DEM) Tales</h1>

			<p>Dope Engineering + Math Tales is an effort make STEM content entertaining, interactive,  approachable and resourceful for underserved students.
      <br><br>
			My role in this project:
      <br>
			Mobile app development, UX/UI design,  character design, curriculum design, episode/animation production, and interactive design.</p>



			<p>DEM Tales is an interactive, animated, STEM enriched mobile platform. DEM Tales is a call-to-action project to support and provide an alternative curriculum to underserved NYC students.</p>



			<p>DEM Tales contains a collection of animated episodes. These episodes present STEM content in a mixture of popular colloquialisms and interaction. Users are held accountable if they wish to reach the conclusions of each episode. For example, if the user is watching an episode, it will pause at a certain point. The user will be prompted to drag and drag an item to a designated portion on the screen. The episode will not continue until this action is performed.</p>

      </div>

    </div>

    <br>
    </br>
    <center>

    <center><div id = "folio-link"><%=link_to 'Back to Portfolio', pages_portfolio_url %></div></center>
    



  </body>
  <html>

app/views/pages/docday.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
      <br>
      </br>
      <br>
      </br>
      <center>
      <div id="project-img">


        <div id="project-row">
          <a href="https://www.demtales.org/">
          		<center>

					<%=image_tag("docdaysteps.gif", width: '500px', height: '800px')%>
					<p>Organizing my thoughts for the doc day website. Knowing that this website will consist of many steps, I just wanted to make sure that I jotted everything down in a logical order.</p>
          <%=image_tag("docday2.jpeg", width: '500px', height: '288px')%>
          <p>Doc Day Online Homepage - Toying around with the placements of things and possible flats that would be appropriate for the project.</p>
					<%=image_tag("docday3.jpeg", width: '500px', height: '350px')%>
					<p>Figuring out what would be the best placement for the "Previous" and "Next" buttons for each step. </p>
				
					
          		</center>

          </a>
        </div>

        <div id="project-des">
          <h1 id="obamify-title">Doc Day Online</h1>

			<p>This is a project that is being built for ITP and NYU Tisch students. While this project is still in the middle of development, feel free to check out some of the wireframes to the left.
      <br><br>
			My role in this project:
      <br>
			UX Designer, Web Developer
      <br>
      A live version of this proejct can be viewed <a id="project-link" href="https://itp.nyu.edu/~tc1886/">here</a>.</p>


      </div>

    </div>

    <br>
    </br>
    <center>

    <center><div id = "folio-link"><%=link_to 'Back to Portfolio', pages_portfolio_url %></div></center>
    



  </body>
  <html>

app/views/pages/frenchcounter.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
      <br>
      </br>
      <br>
      </br>

      <div id="project-img">

        <div id="project-row">
          <a href="https://hidden-hollows-39165.herokuapp.com/">
            <%=image_tag("painting1.png", width: '500px', height: '400px')%>
           <%=image_tag("painting2.jpg", width: '500px', height: '500px')%>
           <%=image_tag("painting3.jpg", width: '500px', height: '400px')%>
           <%=image_tag("painting4.jpg", width: '500px', height: '450px')%>
           <%=image_tag("painting5.jpg", width: '500px', height: '525px')%>
           <%=image_tag("painting6.jpg", width: '500px', height: '250px')%>
       
          </a>
        </div>

        <div id="project-des">
          <h1 id="project-title">French Counter</h1>

          <p>Here is a simple web based project that allows the user to count to 10 in French.</p>
          <br>
          <p>My Role in this project:</p>
          <p>Web Developer, UX and Visual Designer</p>
          <br>
          <p>This project was just an excuse for me to implement and explore React.js.</p>


         
      </div>

    </div>

    <br>
    </br>

    <center><div id = "folio-link"><%=link_to 'Back to Portfolio', pages_portfolio_url %></div></center>
    



  </body>
  <html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>

    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
    
    <h1 id = "name-intro"> Tanya Campbell </h1>
    <h2 id = "job-title">Web Developer, UX Designer, Educator & Illustrator</h2>
    <br>
    <div id = "folio-link"><%=link_to 'View Portfolio', pages_portfolio_url %></div>
    <div id="avatar"><%=image_tag("avatarwhite.gif", width: '100px', height: '150px') %></div>

    <br>
  </body>

</html>

app/views/pages/minion.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body>
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
      <br>
      </br>
      <br>
      </br>
     
      <div id="project-img">


        <div id="project-row">
          <center>
          <%=image_tag("minion.jpg", width: '500px', height: '475px')%>
          <p>Quick Wireframe of DEM Tales Mobile Experience.</p>
          <iframe src="https://player.vimeo.com/video/148035878" width="500" height="288" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <p>Inital Minion Circuit Testing.</p>
          <iframe src="https://player.vimeo.com/video/163103332" width="500" height="288" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
          <p>Minion Circuit User Experience</p>
          <%=image_tag("minion1.jpg", width: '500px', height: '288px')%>
          <p>The actual Minion Circuit..</p>
          <%=image_tag("minion2.jpg", width: '500px', height: '400px')%>
          <p>Stuffing the Minion</p>
          <%=image_tag("minion3.jpg", width: '500px', height: '350px')%>
          <p>We used the Light Blue Bean to Make our Minion Wireless.</p>
          </center>          
             
        </div>

        <div id="project-des">
          <h1 id="project-title">The Minion Circuit</h1>

      <p>The Minion Circuit is a project that aims to take a first step to teaching younger audiences the difference between an opened and closed circuit. When the user holds hands with the minion plush toy, the LED embedded inside the minion lights up; hence the closed circuit. Once the hands of the minion are let go, the LED is no longer lit; hence the opened circuit.

 

      As an electrical engineer and emerging creative technologist, I worked with Yining Shi on The Minion Project.

      My role in this project involved circuit fabrication, UX/UI on The Minion Project website and backend sockets connection coding.</p>



      <p>DEM Tales is an interactive, animated, STEM enriched mobile platform. DEM Tales is a call-to-action project to support and provide an alternative curriculum to underserved NYC students.</p>



      <p>DEM Tales contains a collection of animated episodes. These episodes present STEM content in a mixture of popular colloquialisms and interaction. Users are held accountable if they wish to reach the conclusions of each episode. For example, if the user is watching an episode, it will pause at a certain point. The user will be prompted to drag and drag an item to a designated portion on the screen. The episode will not continue until this action is performed.</p>

      </div>

    </div>

    <br>
    </br>
    <center>

    <center><div id = "folio-link"><%=link_to 'Back to Portfolio', pages_portfolio_url %></div></center>
    



  </body>
  <html>

app/views/pages/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  <body id="portfolio-body">
    <button class="hamburger hamburger--spring" type="button" >
      <span class="hamburger-box"> 
        <span class="hamburger-inner"></span>
      </span>
      <br>
    </button>
    <ul class="burger-links" >
      <div class="link-hover"> 
        <center> 
          <%=link_to 'Home.', root_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Portfolio.', pages_portfolio_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'About.', pages_about_url %> 
        </center> 
      </div>

      <div class="link-hover"> 
        <center> 
          <%=link_to 'Contact.', pages_contact_url %> 
        </center> 
      </div>
    </ul>
    
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br> <br>
    
  <center>

    <div id="row1">

      <div id="obama-project">
        <%=link_to image_tag("obamify.gif", width: '300px', height: '250px'), pages_obamify_url%>
      </div>

      <div id = "demtales">
        <%=link_to image_tag("demtales.png", width: '300px', height: '250px'), pages_demtales_url%>
      </div>

    </div>

    <div id="row2">

      <div id="docday">
        <%=link_to image_tag("inprogress.gif", width: '300px', height: '250px'), pages_docday_url%>
      </div>

      <div id="french">
        <%=link_to image_tag("frenchinprogress.png", width: '300px', height: '250px'), pages_frenchcounter_url%>
      </div>

    </div>


    <div id="row3">

       <div id="outrage">
        <%=link_to image_tag("cowboy.jpg", width: '300px', height: '300px'), pages_outrage_url%>
      </div>

      <div id="minion">
        <%=link_to image_tag("minion.jpg", width: '300px', height: '300px'), pages_minion_url%>
      </div>

    </div>


    <div id="row4">

      <div id="bearhug"> 
        <%=link_to image_tag("BEARHUG.jpg", width: '300px', height: '225px'), pages_bearhug_url%>
      </div>

      <div id="paintings"> 
        <%=link_to image_tag("paintings.jpg", width: '300px', height: '225px'), pages_paintings_url%>
      </div>
    </div>
  
  <br>


  </center>
 


  </body>
</html>

app/views/pages/saycel.html.erb
<a href="http://www.saycel.com/main/"><p>saycel</a></p>